version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=auction
      - POSTGRES_PASSWORD=auction
      - POSTGRES_DB=auction_db
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5434:5432
    volumes:
      - ./data/postgres:/data/postgres
    container_name: db_postgres